name: Jest Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
    - uses: actions/setup-node@v1.1.0
      with:
        node-version: 10.x 
    - name: Setup Node.js for use with actions
    - run: npm ci
    - run: npm run test:unit

